services:
  mongo1:
    image: mongo:7 # 현재 상용 mongodb version 8업그레이드 확인 되면 수정
    container_name: mongo1
    command: [ "--replSet", "replica-set", "--bind_ip_all", "--port", "30001" ]
    ports:
      - 30001:30001
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "30001", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5 # 5번 연속 실패 시 unhealthy
      start_period: 30s

  mongo2:
    image: mongo:7
    container_name: mongo2
    command: [ "--replSet", "replica-set", "--bind_ip_all", "--port", "30002" ]
    ports:
      - 30002:30002
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "30002", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo3:
    image: mongo:7
    container_name: mongo3
    command: [ "--replSet", "replica-set", "--bind_ip_all", "--port", "30003" ]
    ports:
      - 30003:30003
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "30003", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mongo-setup:
    image: mongo:7
    container_name: mongo-setup
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
    command: >
      mongosh --host mongo1:30001 --eval "
      try {
        rs.status();
        print('Replica set already initialized');
      } catch (e) {
        rs.initiate({
          _id: 'replica-set',
          members: [
            { _id: 0, host: 'mongo1:30001' },
            { _id: 1, host: 'mongo2:30002' },
            { _id: 2, host: 'mongo3:30003' }
          ]
        });
        print('Replica set initialized');
      }
      "
    restart: "no"
